### ISSUE TITLE
pass # <<<COULD NOT DECOMPILE: Unknown AST node: <class 'renpy.ast.Camera'>>>>

### ISSUE THREAD

**Issue by pieNICE** [VepsrP/UnRen-Gideon-mod-#10]
Hi! Im really grateful for your .rpyc decompiler!!

Everything did work except for some places. The next line appeared sometimes throughout all of the script:

`pass # <<<COULD NOT DECOMPILE: Unknown AST node: <class 'renpy.ast.Camera'>>>>`

Thought i should tell about this issue

Thanks for your work!!

**Comment by VepsrP** [comment]
yeah, i know it, but I can't solve this problem yet. After all, I am not the original author of the decompiler. I'm just trying to keep the tool up to date as much as my abilities allow.

**Comment by VepsrP** [comment]
i resolve this problem, you can check this out by yourself
